server:
    port: 2020

spring:
  application:
    name: synch-service
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
#      mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html; charset=utf-8
  rabbitmq:
    port: 5672
    host: localhost
    username: springcloud
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    custom:
      appid: 9A064E7A180BB4790F827F546F699BB3
      exchange: synch-exchange
      routingkey: synch-routing
      queue: syn-queue

liumapp:
  filemanager:
    savePath: ../data/

